### PR TITLE
Cache headers added to /maven endpoint

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR is mainly to add the cache related headers to the response for `/maven` endpoint.

This is the Etag that is a UUID based on the response content and a last modified based on the cache date.

This also do (separate commits):

- Moved clear cache to admin
- Only cache 200 responses
- Changed content to Object (rather than casting to String)
- Clean up some unused imports
- Added content type header to pom response

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@Sanne - as per email, you might be interested in this. Specifically the headers part in this commit: https://github.com/quarkusio/registry.quarkus.io/pull/12/commits/18a79bd3835ac7346b033eb0dd7715a1f28e9f31

**Review by gastaldi — APPROVED** [review]
LGTM

@Sanne do you also want to review before we merge this?

**Comment by gastaldi** [comment]
@phillip-kruger can you rebase your PR on latest main?

**Comment by Sanne** [comment]
@gastaldi no, thanks no need. You guys seem to know this stuff way better than me, I just wanted to alert you on difficulties with CDNs but it seems you know :)

**Pull request merged**
