### PR TITLE
Introduce `/client/platforms/all`

### LINKED ISSUE #67: API to list and search for all platform releases known to the registry
The existing API is promoting the latest supported platform streams and releases, targeting new project creation use-case. It's important to keep this API specifically for this use-case.

However, going forward, the registry should allow "browsing" the history of all the recorded platform releases in the registry and downloading their metadata.

### PR DESCRIPTION
**Pull request by gastaldi**
This introduces a new endpoint returning all streams available per platform in a PlatformCatalog format

Fixes #67

### CODE REVIEW

**Comment by gastaldi** [comment]
In registry.quarkus.io, it would give the following output: 

```json
{
  "platforms" : [ {
    "platform-key" : "io.quarkus.platform",
    "name" : "Quarkus Community Platform",
    "streams" : [ {
      "id" : "2.7",
      "releases" : [ {
        "version" : "2.7.1.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-amazon-services-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.7.1.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.7.1.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.7.1.Final" ],
        "quarkus-core-version" : "2.7.1.Final"
      } ]
    }, {
      "id" : "2.6",
      "releases" : [ {
        "version" : "2.6.3.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-amazon-services-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.6.3.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.6.3.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.6.3.Final" ],
        "quarkus-core-version" : "2.6.3.Final"
      } ]
    }, {
      "id" : "2.5",
      "releases" : [ {
        "version" : "2.5.4.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.5.4.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.5.4.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.5.4.Final" ],
        "quarkus-core-version" : "2.5.4.Final"
      } ]
    }, {
      "id" : "2.4",
      "releases" : [ {
        "version" : "2.4.2.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.4.2.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.4.2.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.4.2.Final" ],
        "quarkus-core-version" : "2.4.2.Final"
      } ]
    }, {
      "id" : "2.3",
      "releases" : [ {
        "version" : "2.3.1.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.3.1.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.3.1.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.3.1.Final" ],
        "quarkus-core-version" : "2.3.1.Final"
      } ]
    }, {
      "id" : "2.2",
      "releases" : [ {
        "version" : "2.2.2.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.2.2.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.2.2.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.2.2.Final" ],
        "quarkus-core-version" : "2.2.2.Final"
      } ]
    } ],
    "current-stream-id" : "2.7"
  } ]
}
```

**Comment by aloubyansky** [comment]
It looks like it's returning the last recommended release per stream. If that's the case, perhaps, it should not be called `all` or is also meant to accept a parameter to actually return all the releases, which is what the original request was about, afaiu.

**Comment by gastaldi** [comment]
> It looks like it's returning the last recommended release per stream.

No, it should be returning all streams and releases, see https://github.com/quarkusio/registry.quarkus.io/pull/71/files#diff-c837a67be26a3da58d4296ab1b9d7dd3665b8dc8c02c7a4644025f019f58b513R50

Are you seeing just the last recommended release?

**Comment by aloubyansky** [comment]
The code looks good, right. I originally looked at the sample result in your comment.

**Comment by gastaldi** [comment]
But your observation makes sense, I'll have a deeper look at the method nevertheless

**Comment by gastaldi** [comment]
@aloubyansky You're right, I fixed this in https://github.com/quarkusio/registry.quarkus.io/commit/3c171b737c1ea91da37f7d6babcdd81d0e0e0fb2

**Pull request merged**
