### PR TITLE
Expose an example config.yaml over the registry's REST api

### PR DESCRIPTION
**Pull request by gastaldi**
@jmartisk I have played with it and I don't think we need to introduce a new property to expose this configuration. IMHO it doesn't do any harm if it is always exposed.

I have refactored the tests a bit and used the model classes instead of relying on the String output.  Let me know what you think about it

### CODE REVIEW

**Comment by jmartisk** [comment]
AFAIR @aloubyansky asked for this not to be exposed in production deployments, so let's hear his opinion.

**Comment by aloubyansky** [comment]
One of the concerns that @maxandersen raised in Jan's PR was that it reveals details of the internal infrastructure, which isn't desired in prod.

**Comment by gastaldi** [comment]
AFAIK the URL returned in the YAML is the same used to access it and it's configured via `QUARKUS_REGISTRY_MAVEN_REPO_URL` environment. Can you elaborate?

**Comment by aloubyansky** [comment]
In that case, it's fine, thanks for checking.
A possible concern could be we expose an endpoint w/o a requirement in production. Somebody may discover it and start relying it, while we may for some reason change or remove it.

**Comment by gastaldi** [comment]
> A possible concern could be we expose an endpoint w/o a requirement in production. Somebody may discover it and start relying it, while we may for some reason change or remove it.

I don't think that's the case here, we're just presenting a valid client configuration for the requested registry :)

**Pull request merged**
