### PR TITLE
Introduce welcome page in /maven

### LINKED ISSUE #263: Introduce a welcome page in /maven
When navigating to https://registry.quarkus.io/maven I get a 404. It would be nice to have a welcome page, stating that this is a Maven repository and the artifacts it provides (if possible) along with instructions to configure in corporate Nexus' if needed

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #263

Screenshot 2024-11-05 at 16 08 42

### CODE REVIEW

**Comment by aloubyansky** [comment]
Is the text supposed to be re-usable between registry.quarkus.io and registry.quarkus.redhat.com?

Otherwise, I'd suggest something like:

This endpoint provides [Quarkus platform](https://quarkus.io/guides/platform) and [extension metadata](https://quarkus.io/guides/extension-metadata) in the form of Maven artifacts for Quarkus Dev Tools clients, such as [code.quarkus.io](https://code.quarkus.io/) and [Quarkus CLI](https://quarkus.io/guides/cli-tooling).

**Comment by gastaldi** [comment]
> Is the text supposed to be re-usable between registry.quarkus.io and registry.quarkus.redhat.com?

Yes, it's supposed to be merely informative in case anyone browses to `/maven` instead of getting the confusing 404.

Here is the updated screenshot with your suggestion:

Screenshot 2024-11-05 at 16 53 38

**Comment by aloubyansky** [comment]
Then we probably shouldn't link to code.quarkus.io?

Thanks for this, btw!

**Comment by gastaldi** [comment]
How about linking to https://quarkus.io/guides/extension-registry-user instead? eg.

This endpoint provides <a href="https://quarkus.io/guides/platform">Quarkus platform</a> and <a href="https://quarkus.io/guides/extension-metadata">extension metadata</a> in the form of Maven artifacts for <a href="https://quarkus.io/guides/extension-registry-user">Quarkus Registry user clients</a>

**Pull request merged**
