### PR TITLE
Use latest createdAt on metadata.xml

### PR DESCRIPTION
**Pull request by gastaldi**
This enables the service to run in more than 1 replica

### CODE REVIEW

**Comment by gastaldi** [comment]
I don't understand why CI freezes after running the AdminApiTest

**Comment by aloubyansky** [comment]
Do all the catalogs the registry provides share the same timestamp, which is the time the last extension or platform was updated?
And now it's querying the database on every request?

**Comment by gastaldi** [comment]
Yeah, I know it's not the perfect solution but it works. I could cache it for a specific timeframe but I wouldn't know when to invalidate it if we're running on multiple replicas.

Another idea: maybe we could read that value from a ENV parameter and restart the app when the value changes, but I am not fully convinced in this strategy yet.

**Comment by gastaldi** [comment]
I'll give it more thought about it. Closing now

**Pull request closed without merging**
